version: '3.9'

services:
  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioAkey
      - MINIO_ROOT_PASSWORD=minioSkey
    volumes:
      - ./minio_data:/data
    ports:
      - 9000:9000
      - 9001:9001

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017  
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./mongodb_data:/data/db

  web:
    build: ./backend
    user: "node:node"
    environment:
      - APP_PORT=${APP_PORT:-3000}
    volumes:
      - "./backend:/app/backend"
      - "./frontend:/app/frontend"
    ports:
      - "3000:3000"

volumes:
  minio_data:
  mongodb_data: